### ISSUE TITLE
Right Click interaction

### ISSUE THREAD

**Issue by djoveryde** [gamerforEA/AppEng-FakePlayers#1]
It seems right clicking with an AppEng block instantly crashes the client. I'm trying to confirm if the fault still exists even after I switch AppEng back to the non "FP" version. 
Only seems to affect clientside, so not sure if its an interaction between the untouched client version and the patched server version.

SIDE NOTE: Could you take a look at perhaps patching ProjectE up also as that full on bypasses protection with its right clicking and "G" key special abilities on items.

**Comment by gamerforEA** [comment]
On my client/server, everything works fine.
