### ISSUE TITLE
дюп rv3-beta-6

### ISSUE THREAD

**Issue by 008** [gamerforEA/AppEng-FakePlayers#3]
не корректно закрывается GUI, модфикс не помогает...
Получается один чел открывает GUI, второй в этот момент ломает блок с которого GUI.
https://www.youtube.com/watch?v=XZCuWVJg8Sw
Помоги пожалуйста.

**Comment by gamerforEA** [comment]
Фикс у меня есть, но опубликую только через пару недель. Подсказка, как исправить:
1) Взгляните на 2 цикла в GridStorageCache.removeCellProvider(...).
2) Реализуйте метод NetworkInventoryHandler.addNewStorage(...) наоборот.
