### ISSUE TITLE
Useless entity class check

### ISSUE THREAD

**Issue by onyn** [gamerforEA/AppEng-FakePlayers#6]
Can't understand what class really should be on the right side of `instanceof` operator.

https://github.com/gamerforEA/AppEng-FakePlayers/blob/75770f40fbaf7f8375886ff76070675f8f5fc6c7/src/main/java/appeng/spatial/StorageHelper.java#L227-L244

**Comment by gamerforEA** [comment]
https://github.com/gamerforEA/AppEng-FakePlayers/commit/1155be3d917590779467680f8e910d28977914b5
