### ISSUE TITLE
Bug patch code merge request

### ISSUE THREAD

**Issue by xsun2001** [gamerforEA/AppEng-FakePlayers#7]
Hi, gameforEA.
Your AE2 version is amazing, but it depends on Bukkit to work. I’d like to merge some bug patch code you wrote to my own repo, which requires nothing but Forge. I need your premission to use your work. And I want to know what should I do or pay attention to, so that I can use your code correctly without infringing on your proper rights and interests. Thanks in advance.
Sorry for my poor English.

**Comment by xsun2001** [comment]
Since you have not objected to my proposal, I will temporarily assume that you have agreed to my request. I will keep this issue open until you respond to it.

**Comment by gamerforEA** [comment]
Oh, sorry. Issues/PRs in my repositories are rare events so I do not check new issues/PRs existance.
You can use my AE2 version.
